temp test to check if builds re generated

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -6,8 +6,8 @@ on:
         description: 'Tag name for release'
         required: false
         default: prerelease
-  #push:
-  #  branches: [ main, feature/* ]
+  push:
+    branches: [ manodnyb/addPrerelease3 ]
 
 
 jobs:
@@ -130,7 +130,7 @@ jobs:
         run: |
           TAG_NAME=${{ github.ref_name }}
           # change to feature later
-          FEAT_NAME=$(echo $TAG_NAME | sed 's/feature\///')
+          FEAT_NAME=$(echo $TAG_NAME | sed 's/manodnyb\///')
           echo "FEAT_NAME=$FEAT_NAME" >> $GITHUB_ENV
           echo "TAG_NAME=pre-$FEAT_NAME" >> $GITHUB_ENV
       - if: github.ref_name == 'main'
@@ -151,38 +151,38 @@ jobs:
           cat CHANGELOG.md | perl -ne 'BEGIN{$/="\n\n"} print; exit if $. == 1' >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
 
-  publish:
-    needs: [ generate_artifact_toolkit, generate_artifact_core, generate_artifact_q, generate_changelog ]
-    env:
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      GH_REPO: ${{ github.repository }}
-      FEAT_NAME: ${{ needs.generate_changelog.outputs.feature }}
-      TAG_NAME: ${{ needs.generate_changelog.outputs.tagname }}
-      AWS_TOOLKIT_VERSION: ${{ needs.generate_changelog.outputs.version }}
-      BRANCH: ${{ github.ref_name }}
-      AWS_TOOLKIT_CHANGES: ${{ needs.generate_changelog.outputs.changes }}
-    runs-on: ubuntu-latest
-    permissions:
-      contents: write
-    steps:
-      - uses: actions/checkout@v4
-      - uses: actions/download-artifact@v4
-      - name: Delete existing prerelease
-        # "prerelease" (main branch) or "pre-<feature>"
-        if: "env.TAG_NAME == 'prerelease' || startsWith(env.TAG_NAME, 'pre-')"
-        run: |
-          echo "SUBJECT=AWS Toolkit ${AWS_TOOLKIT_VERSION}: ${FEAT_NAME:-${TAG_NAME}}" >> $GITHUB_ENV
-          gh release delete "$TAG_NAME" --cleanup-tag --yes || true
-      - name: Publish to GitHub Releases
-        run: |
-          envsubst < "$GITHUB_WORKSPACE/.github/workflows/prerelease_notes.md" > "$RUNNER_TEMP/prerelease_notes.md"
-          gh release create $TAG_NAME --draft --prerelease --notes-file "$RUNNER_TEMP/prerelease_notes.md" --title "$SUBJECT" --target $GITHUB_SHA plugin-toolkit-*/*.zip
-      - name: Publish core
-        run: |
-          gh release upload $TAG_NAME plugin-core-*/*.zip
-      - name: Publish Q
-        run: |
-          gh release upload $TAG_NAME plugin-amazonq-*/*.zip
-      - name: Publish Toolkit Standalone
-        run: |
-          gh release upload $TAG_NAME plugin-toolkit-standalone-*/*.zip
+#  publish:
+#    needs: [ generate_artifact_toolkit, generate_artifact_core, generate_artifact_q, generate_changelog ]
+#    env:
+#      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#      GH_REPO: ${{ github.repository }}
+#      FEAT_NAME: ${{ needs.generate_changelog.outputs.feature }}
+#      TAG_NAME: ${{ needs.generate_changelog.outputs.tagname }}
+#      AWS_TOOLKIT_VERSION: ${{ needs.generate_changelog.outputs.version }}
+#      BRANCH: ${{ github.ref_name }}
+#      AWS_TOOLKIT_CHANGES: ${{ needs.generate_changelog.outputs.changes }}
+#    runs-on: ubuntu-latest
+#    permissions:
+#      contents: write
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: actions/download-artifact@v4
+#      - name: Delete existing prerelease
+#        # "prerelease" (main branch) or "pre-<feature>"
+#        if: "env.TAG_NAME == 'prerelease' || startsWith(env.TAG_NAME, 'pre-')"
+#        run: |
+#          echo "SUBJECT=AWS Toolkit ${AWS_TOOLKIT_VERSION}: ${FEAT_NAME:-${TAG_NAME}}" >> $GITHUB_ENV
+#          gh release delete "$TAG_NAME" --cleanup-tag --yes || true
+#      - name: Publish to GitHub Releases
+#        run: |
+#          envsubst < "$GITHUB_WORKSPACE/.github/workflows/prerelease_notes.md" > "$RUNNER_TEMP/prerelease_notes.md"
+#          gh release create $TAG_NAME --draft --prerelease --notes-file "$RUNNER_TEMP/prerelease_notes.md" --title "$SUBJECT" --target $GITHUB_SHA plugin-toolkit-*/*.zip
+#      - name: Publish core
+#        run: |
+#          gh release upload $TAG_NAME plugin-core-*/*.zip
+#      - name: Publish Q
+#        run: |
+#          gh release upload $TAG_NAME plugin-amazonq-*/*.zip
+#      - name: Publish Toolkit Standalone
+#        run: |
+#          gh release upload $TAG_NAME plugin-toolkit-standalone-*/*.zip
